language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "hostettler-github"
    
jobs:
  include:
    - stage: Prepare
      script:
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install
      - mvn sonar:sonar -Dsonar.projectKey=hostettler_jdd -Dsonar.organization=hostettler-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=10de2947edc0e089a82360cb2d1aa97482fafc28
     