language: java
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: hostettler-github
env:
  global:
  - secure: Sksudy8U/lZ+Ap+oWRZaC4kAHIgzPQwjnc+A0up+Hs0VWeXVgyoaUDUkiuOdgNcTbzakiFpqubHsFaxdq8Pi7N7NHbCrBGpryQ+hldrsY3TWo5WOCI89CQwRfXYZyQJRe4j1cmw2PJiCFi6wlCyxO70OfMit5OE4efr1GWGAuFpZOIXiR5wZutYuIXYjRsFPeOeiKhkllBmnkNArmQENGivj3bM2/IzN9bTkcjTVRiSyykI6YKU69e/Ugt8caN0XkD1FToybDXpKl/BBqE/Hoh8JuvtJYGfgdsx4QKI+H94wCXAQ3MDVaCKKZdVbJuQbWTT2USWN6+r9Ylhn6fLRIeUkoc76gxr8kepE6ZUkiQzYRJFZoHpECdNgowBez/2cNffFGvjhsoNI+fdlWaMZSak2tg8GEi3qKXsoev9wc6nNGykHEATyhxJeMyKxEpf7H9XSh3Yk2yDL88L5A04UDAWfflkJRotXpiDlrnkWKjPevCmUvcecbzIrK6GR6CGrqbqfNFbmvpUfUc1tjrR23WkpIEEAntEP6lMEzxJGrB0bcd9B0LHdSbgWwfNDN+3b6h4tbhTc97bbtSv2IKD6x914zotHJ962pZkVwAPxN1lR43xQ4qHedGbuve3JuR4Bpf/scwCJUBmSB9aqtxowT5fN//cAuGOJEVo0lCaZx3U=
  - secure: NV9k1wc1KlJUHQRFmCNEnfvHz4rvykPMx0F+/IHPgHWTt6VEcuYtNJ/4JQ+h9GES+6scry4QmGja95U0WjGH2Z99tOT1EjbVpim7vw1XFi/wq+urbZBIaV3wQSxFJ1UH+NlcFPZupr+i/m6F8kZ6tqM08ogeeEtRGwcS/hbSF5sDsLaaU6RoeqIY+T/DvyQ0+iLzs9lO6e5zhQsiRfXrPfReggRKqOsAvZ2ilzjhF8K6eiELzFn/O5LJK1z3M+pdY8Fh2kbLni6XFJwGjmsvz0NgVd+b6qy5/hBNadJw9c9C+lwZ66bB3Ak3iqfKScxs3EfGV4WFwWoim8dvaiZbjWJsRTScdB99liEWTzGM5MJmgUUGoYBeZ46v/3lBkgVfFIkLf43JpeXRhxXat9EwY68zHAJIAZaqck3a31nPEyjZAeg8OQ6AxYE6e9CJuV3oQgbPFJFT5rQtMFusmDKYCzN++jERUeWSzSD0C/dLIfTRshdrQ/1WJCsmMr6WCXOEBKspgPUDZLQ2vEPYE81usCHQWX9vyxSDew5mFfB6QbCzPc4YvVsZEmnokFxRq/tHBXoAYjsVaQCZFf5WwwCW81cuMDIopbh2wT/jsV/kW3oIJ5Hz9v4M3CNbkPJ52KsUmO3Trn9MocSmSUs+qM6QDLiihUcGCPMix22H5/FdoMg=
  - secure: sY0KGgbqxL/y12hpFz4vSOMEEzTxyWopaB5AMUi51dNFI8uJzIOKHyUwz9aG8x4c9rz18LhNOE3KN5p7U82q3osXJBMnVzZV5Ui59vcV35bzRMC6gUV3OwKaX63uzgyA9FQmmYVYzhIRQBLByMc345WdEuEM+3mFjFAF62qlMfogbgm2GZroS22l7/OVZqpjAof70ynKMufByOOoOqnr/pfmxEIfn09BI7GIOEpZB7s15heh+sLBWQas4hQU9t0LrA/pzgfP29JtzgOImYQe0ONWKoVjU5U8n+OxQ82FpL0Lq+TZRNm5zgcf19a1qbryj8zKvYPffMKAFjX0ucM96Xaf6kcPVunymXrMQmFHTpYpLAP0PNPWE8oubtFHL9ctN6IovOAvITq4JyA52WAN1jyYKLLt8cBaZWCST9D5wiYw4scDvBuMWX+SquK2qqt5YmjFQj8QWPuS55ySNKP+RcfwWh4ljbJKrIgvJMvI2PC5iR0E+JG9r1fCUJiPW5mlBDgRIOdb2EuREMRe4tXfbTuHaFdNjkFGQvWgTmZfNd6rzscnqBvbNURK/BokBzLcmRPMNvYmPR1wGtzFk1ItUJJ+PLsA4YoUIgaxZnjsKfxGfaMGUXBTpJZTrATrBiidAVjtHtbz6PICaw9YgxsfuP76K3zuWP1XzIkN4OZ+cPE=
  - secure: s1FhBeAKyYetM8f8PvxHubQ0ynscete98N0qKlVjGVx8rGwlB/1FGqr6ubJiVhTMHHTHfHLfPaWgbCmZ+kGnFLQF866nWgXRNhzHQAYk//983eQfzemB6fIpAwUO3G9V4SeJQPXW9ydaIxjqtPkYsIrocn0UYtHIkQn217/Tfg8fPLxDxZzMC9ZCF/I+HQp3NUXDbqIrkjbOLbaf6RymuYKrxaD7Hge/EMpo/6X43XHtbe2esXYk247anAEGkixbOdFkTcE1FolQ0ap5+QBc8w8U8zy0eKREVd7g8yhbEmKfjPpeUi6dPCBEfdqTo8xxtHdTjkSoy8yMkq25GdauUyXJfnVFeDxKSX/lGUOxC3txqwZcpW9OhqLmEGLgKJ3UPvD+nRnqNjzadf+ui/QaBICAvTmfu8+Z6HR3Ly1KuEomEOa0RQjDL9vo2Knp7RbhB8O1VayCGdJeWQ6N7A1hl96yVh33ynhHV7taEbnEUGwy7JPyZGUrN0k7DQEWmYhjBDsdWyf4O2pMrzgdFsHkI/SjPv7XGaGnjwJb4bgAm4LWdjQUdRWmVMW4t1GYOb5xE/Xr1Wmx9JLx4XxMljtWBJ3FE8leAMygpp9Poi1vgr1GfqodBYixonclVx4BanMynnisLlFclq+wuXZBQNlA1FpfaUubH1+MuKv3d/MrZbg=
  - secure: YtGejlm7orukm0b3XEYSp2o6uqmMTMrgu23gVk7LMJYG937+ybggvKLb7LpypXBNxK/0v6aOlV4YqlTK46T4c+LXPAkXzXHwBAQpFZEOJ+0KOetf5WBI3i+X50125WyjcfGIMvaHcLe/pfjP3F/0dcOH1IIBN2cYOEZ+LiRPsBceVL1evQ4wbWe9TnZhfEm8Y8niwv0Rd7n+/vlXsNtr5Au5JVNNMVhGAM9Tu60SDvoF4iAI+6IrEUD9Lpk7GxCsieWcq6VPm6ftyK8jhX2GKNnJwp69evB+vYJvj6waNgBYRtC++RLlQX/E2beGasgWUxEcWFo8l7ZdNqDJMyGFfEZoNN8O4kHL6/c266F8W3OFBHXOjQykyaeGl7osVQ/e01jBfHc9gpb4TGefQZE48m6NDMzwGLVSjsKfNpqjlas3KROvDt6PTJwEcuW2gzjokfxuMSuH8IxytM11UHcioXtHavIV5i0Cpc/ZJg92JNo77xXK5/MjxJO00MepBUtTOEZdgHJdlmoYLc7yp69upVJYpXd+uYB1Mx9zGO558lW69BWPpk7KfygNbAn2IwcFI9AWLlrk2W9pwORDw6ihZ128rdRn7i68OPruaG9KpEwIiczl/2mNGtp6hGMRQZAIfZQbIKMhq6kJ7Tg7hlcIK1J4Hy3vkmWU6a4l089UGYs=

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: hostettler/jdd
      tags: true
      jdk: openjdk11

script: mvn --settings .travis/maven-settings.xml clean  verify

jobs:
  include:
  - stage: Prepare
    script:
    - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - stage: Build
    script:
    - mvn install  --settings .travis/settings.xml 
    - mvn sonar:sonar -Dsonar.projectKey=hostettler_jdd -Dsonar.organization=hostettler-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=10de2947edc0e089a82360cb2d1aa97482fafc28
